baseURL = 'https://maindak.is-a.dev/'
languageCode = 'en-us'
title = "The Tadpole's Swamp"
theme = 'risotto'
paginate = 3
copyright = "𓆝 𓆟 𓆞"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "swamp"

# Sidebar: about/bio
[params.about]
title = "𓆏 // maindak"
description = "A murky personal website to archive my ramblings."

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/masroof-maindak"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:mujtaba.asim.amin@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "Discord"
url = "https://discord.com/users/589511603289063434"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
