page_title = "The Tadpole's Swamp"
name = "Mujtaba Asim"
username = "@masroof-maindak"
bio = "Goddamned Vagrant."
email = "mujtaba.asim.amin@gmail.com"
github = "https://github.com/masroof-maindak"
desc = "Weaver of bits. Apprentice alchemist. Ostensibly erudite systems hermit."
footer = "© 2025 Mujtaba Asim"
theme_name = "swamp-light"
